twist_servo_debugger:
  ros__parameters:
    remote_controller_topic: "/rm_manager/remote_control"
    output_topic: "/servo_node/delta_twist_cmds"
    channels: [2, 3]
    axes: ["linear.x", "linear.y"]
    max: [0.5, 0.3]
    invert: [false, false]
